name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  quality-gate:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      uses: cypress-io/github-action@v6
      with:
        runTests: false

    - name: Run Lint
      run: npm run lint

    - name: Run E2E Tests
      uses: cypress-io/github-action@v6
      with:
        install: false
        browser: chrome